name: GNULIB Patch Tests
on:
  push:
    branches-ignore:
      - trash
  schedule:
    - cron: '30 5 * * *'

env:
  CI_REQ_DOTNET_SDK_VER: 6.0.401
  NUKE_TELEMETRY_OPTOUT: 1
  MSYS: "winsymlinks:native wincmdln"
  MSYS2_ARG_CONV_EXCL: "/a;/b;/c;/d;/e;/f;/g;/h;/i;/j;/k;/l;/m;/n;/o;/p;/q;/r;/s;/u;/v;/w;/x;/y;/z;/0;/1;/2;/3;/4;/5;/6;/7;/8;/9;/A;/B;/C;/D;/E;/F;/G;/H;/I;/J;/K;/L;/M;/N;/O;/P;/Q;/R;/S;/T;/U;/V;/W;/X;/Y;/Z"
  MSYS2_PATH_TYPE: inherit
  WLB_BASE_FOLDER: "d:/WLB"
  MSYSTEM: UCRT64
  MSYS_PATH: d:/msys64

jobs:
  get_patch_matrix:
    uses: ./.github/workflows/do_build.yml
    with:
      BuildPkg: script
      Script: f_template_build_file.sh gnulib_dump_patches
  gnulib_test_all_patches:
    name: Test All Patches Together
    uses: ./.github/workflows/do_build.yml
    with:
      BuildPkg: script
      Script: .github/gnu_patchtest.sh all_patch

  gnulib_test_patch:
    name: Test Single
    needs: get_patch_matrix
    strategy:
      fail-fast: false
      matrix:
        PatchName: ${{ fromjson(needs.get_patch_matrix.outputs.ScriptRes) }}
        Mode: [branch, patch]
    uses: ./.github/workflows/do_build.yml
    with:
      BuildPkg: script
      Script: .github/gnu_patchtest.sh ${{ matrix.Mode }} '${{ matrix.PatchName }}'
