name: GNULIB Patch Tests
on:
  push:
    branches-ignore:
      - trash
  schedule:
    - cron: '30 5 * * *'

env:
  CI_REQ_DOTNET_SDK_VER: 6.0.401
  NUKE_TELEMETRY_OPTOUT: 1
  MSYS: "winsymlinks:native wincmdln"
  MSYS2_ARG_CONV_EXCL: "*"
  MSYS2_PATH_TYPE: inherit
  WLB_BASE_FOLDER: "d:/WLB"
  MSYSTEM: UCRT64
  MSYS_PATH: d:/msys64

jobs:
  get_patch_matrix:
    uses: ./.github/workflows/do_build.yml
    with:
      BuildPkg: script
      Script: .github/gnu_patchtest.sh gnulib_dump_patches
      NoDebugBuild: true
  gnulib_source_cache:
    runs-on: windows-2022
    defaults:
        run:
          shell: pwsh
    steps:
      - name: clone srcs
        run: git clone git://git.sv.gnu.org/gnulib.git d:/WLB/gnulib.git
      - name: Cache gnulib bare repo
        uses: actions/cache@v4
        with:
          path: d:/WLB/gnulib.git
          key: gnulib-bare

  gnulib_test_all_patches:
    name: Test All Patches Together
    uses: ./.github/workflows/do_build.yml
    with:
      BuildPkg: script
      NoDebugBuild: true
      Script: .github/gnu_patchtest.sh all_patch

  gnulib_test_patch:
    name: Test Single
    needs: get_patch_matrix
    strategy:
      fail-fast: false
      matrix:
        PatchName: ${{ fromjson(needs.get_patch_matrix.outputs.ScriptRes) }}
        Mode: [branch, patch]
    uses: ./.github/workflows/do_build.yml
    with:
      NoDebugBuild: true
      BuildPkg: script
      Script: .github/gnu_patchtest.sh ${{ matrix.Mode }} '${{ matrix.PatchName }}'
