name: coreutils Tool Build
on:
  push:
    branches-ignore:
      - trash
  schedule:
    - cron: '30 5 * * *'

jobs:
  build:
    uses: ./.github/workflows/tool_build.yml
    with:
      ToolName: coreutils
      
